### POST a new adoptive
POST http://localhost:8080/api/adoptives
Content-Type: application/json

{
  "name" : "Égeto Napsugár",
  "address" : "4400 Nyíregyháza, Keleti park 32."
}

### PUT update an adoptive
### Pl. költözés miatti címváltozás. A nevet is engedi változtatni,
### férjezés-válás esetén változhat, így nem célszerű letiltani a funkciót.
PUT http://localhost:8080/api/adoptives/1
Content-Type: application/json

{
  "name" : "Elektrom Ágnes",
  "address" : "6000 Kecskemét, Fő tér 5."
}


### GET all adoptives
GET http://localhost:8080/api/adoptives
Accept: application/json

### GET adoptives by existing name
GET http://localhost:8080/api/adoptives?namePart=Emma
Accept: application/json

### GET adoptives by invalid name

GET http://localhost:8080/api/adoptives?namePart=Kovács
Accept: application/json

### GET adoptives by city

GET http://localhost:8080/api/adoptives/adoptivesbycity?city=Budapest
Accept: application/json

### GET adoptives by wrong city

GET http://localhost:8080/api/adoptives/adoptivesbycity?city=Békéscsaba
Accept: application/json

### GET adoptive by ID with hamsters

GET http://localhost:8080/api/adoptives/1/hamsters
Accept: application/json

